### Тест 2: Проверка маршрута partner/orders/items (PATCH запрос)
PATCH http://localhost:8000/api/v1/partner/orders/items
Content-Type: application/json
Authorization: Token 1dd27c387e5e902bcb655c94019decb07384f373

{
  "order_id": 4,
  "updates": [
    {
      "item_id": 78,
      "quantity": 8
    },
    {
      "item_id": 67,
      "quantity": 0
    }
  ]
}
